# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gossip.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgossip.proto\x12\x05proto\"\x0f\n\rGossipMessage\"$\n\x11IncrementResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x10GetCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32\x91\x01\n\rGossipService\x12=\n\tIncrement\x12\x14.proto.GossipMessage\x1a\x18.proto.IncrementResponse\"\x00\x12\x41\n\x0eGetGossipCount\x12\x14.proto.GossipMessage\x1a\x17.proto.GetCountResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gossip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GOSSIPMESSAGE']._serialized_start=23
  _globals['_GOSSIPMESSAGE']._serialized_end=38
  _globals['_INCREMENTRESPONSE']._serialized_start=40
  _globals['_INCREMENTRESPONSE']._serialized_end=76
  _globals['_GETCOUNTRESPONSE']._serialized_start=78
  _globals['_GETCOUNTRESPONSE']._serialized_end=111
  _globals['_GOSSIPSERVICE']._serialized_start=114
  _globals['_GOSSIPSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
